version: '3'

services:
  web:
    build: .
    command: daphne pongproject.asgi:application --bind 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379